### ISSUE TITLE
what's the editor theme?

### ISSUE THREAD

**Issue by RezaBani** [ibokuri/zig-by-example#8]
Hi, this is not an actual issue, just a question:

what is the snippets theme in the site? it looks great.

for example snippets in this page: https://zig-by-example.com/while

**Comment by ibokuri** [comment]
Hey @RezaBani, the site is a fork of the awesome [Go By Example](https://gobyexample.com/) website ([source](https://github.com/mmcgrana/gobyexample)).

**Comment by RezaBani** [comment]
Sry I had dark reader on so that changed the website and snippets colored to something awsome that probably doesn't exist yet...
